pipewire/thread.c: only handle reset_on_fork if SCHED_RESET_ON_FORK is defined
This fixes a missing definition error in thread.c:

../src/pipewire/thread.c:129:30: error: use of undeclared identifier 'SCHED_RESET_ON_FORK'
  129 |         SPA_FLAG_UPDATE(new_policy, SCHED_RESET_ON_FORK, reset_on_fork);